# ===================================
# APPLICATION
# ===================================
spring.application.name=security

# ===================================
# SERVER
# ===================================
server.port=8080

# ===================================
# POSTGRESQL
# ===================================
spring.datasource.url=jdbc:postgresql://localhost:5432/securitydb
spring.datasource.username=postgres
spring.datasource.password=pominiG
spring.datasource.driver-class-name=org.postgresql.Driver

# ===================================
# JPA
# ===================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl=true
spring.jpa.show-sql=true

# ===================================
# FLYWAY
# ===================================
spring.flyway.enabled=true

jwt.secret=KJASHD8923HJKASHD8923HJKAHSKD8923
jwt.expiration=86400
